### PR TITLE
Javascript Program to Convert Celsius to Fahrenheit

### PR DESCRIPTION
**Pull request by Avinashluhana**

### CODE REVIEW

**Comment by naveennamani** [comment]
Please make your contribution based on the repo. These kind of scripts are not allowed or required in this repo. I'll be happy to help you if you're interested in contributing.

**Comment by Avinashluhana** [comment]
Can I get to know, why you marked my contribution as spam?

**Comment by naveennamani** [comment]
You can please check the readme to know what this repository is about and what kind of contributions you can make.

If you're even more interested you can check the successfully closed PRs to know why your contribution is marked as spam.

I'm once again iterating that if you want to contribute I'm glad to help you. But just adding some random scripts in the name of contribution is not good. It is a waste of time and efforts for you as well as me.

Hope you understand, and happy hacktoberfest.

**Comment by Avinashluhana** [comment]
Hey Naveen, What kind of contributions are you accepting?

**Comment by naveennamani** [comment]
This repo is a collection of scripts which can be used to generate offline documentation for various projects. You can go through the readme and check various kinds of repositories. If you are interested I suggest you the following repo for your contribution.

Hasura: https://hasura.io/docs
Repo: https://github.com/hasura/graphql-engine/tree/master/docs

You can go through the package.json file in the repo to check the build scripts.
You can open this repository in gitpod.io which will setup all dependencies and run the necessary cli script, so that you can directly add the required details.

If you're stuck at any step please reply to this thread or create an issue.

**Comment by naveennamani** [comment]
If you know of any websites where the documentation website is open source on github, you can add them to TODO.md file.

You can check the sample details to be added by looking at the TODO.md file.

https://github.com/naveennamani/offline-docs/blob/main/TODO.md

**Pull request closed without merging**
